### ISSUE TITLE
Clicking on the nickname input refreshes the page and clears the focus

### ISSUE THREAD

**Issue by braaar** [HacklabJKL/visitors#21]
Steps to reproduce:

1. Open https://lab.jkl.hacklab.fi:5944/visitors/
2. Click the nickname field with the mouse (or tap it with mobile)
3. The page refreshes, and the field is no longer focused

Note: The field can be focused with the tab key.

I suspect the issue comes from this `a` element which triggers whenever you click inside of it. I don't understand its purpose. Does the `template` element in `index.html` turn into an anchor?

![Screenshot 2022-05-23 at 10 45 39](https://user-images.githubusercontent.com/5765650/169769347-407e4386-4668-4300-8b6a-6d65add9ac84.jpg)

**My computer where the issue occurs**
MacOS Monterey 12.0.1
Google Chrome Version 101.0.4951.64 (Official Build) (arm64)

**My phone where the issue occurs**
Google Pixel 4a
Android 12
Google Chrome Version 101.0.4951.64

Issues occured at the hacklab, connected to the hacklab wifi.

**Comment by PetteriAimonen** [comment]
I think the issue is missing `</a>` here:
https://github.com/HacklabJKL/visitors/blob/master/dist/index.html#L23

**Comment by zouppen** [comment]
> I think the issue is missing `</a>` here: https://github.com/HacklabJKL/visitors/blob/master/dist/index.html#L23

Fixed the tag. Please test again @braaar

**Comment by braaar** [comment]
> > I think the issue is missing `</a>` here: https://github.com/HacklabJKL/visitors/blob/master/dist/index.html#L23
> 
> Fixed the tag. Please test again @braaar

It's working! Thanks for the fix!
